import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import dynamic from "next/dynamic";
import { generateClasses } from "@/utils/generatePojo";
import JsonEditor from "@/components/JsonEditor";
import JavaEditor from "@/components/JavaEditor";

const MonacoEditor = dynamic(import("react-monaco-editor"), { ssr: false });
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [jsonInput, setJsonInput] = useState("{}");
    const [page, setPage] = useState(-1);
    const [showSettings, setShowSettings] = useState(false);
    const [pojoClasses, setPojoClasses] = useState<
        Array<{ className: string; value: any }>
    >([]);

    function generatePojo() {
        setPojoClasses(generateClasses(JSON.parse(jsonInput)));
        setPage(0);
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className={`${inter.className} bg-gray-900 min-h-screen flex flex-col text-white px-4`}
            >
                <header className="font-bold uppercase container mx-auto border-gray-800 border-b flex justify-between">
                    <div className="py-4">POJO Generator</div>
                    <div className="flex flex-col justify-center">
                        <button className="py-2 px-4 bg-indigo-600 hover:bg-indigo-500 transition duration-300 rounded-full">
                            Settings
                        </button>
                    </div>
                </header>
                <nav className="container mx-auto flex flex-wrap gap-1 pt-4">
                    <button
                        className={`shadow-md py-2 px-4 rounded-sm ${
                            page === -1 ? "bg-gray-600" : "bg-gray-800"
                        }`}
                        onClick={() => setPage(-1)}
                    >
                        Json Editor
                    </button>
                    {pojoClasses.map((pojoTab, i) => (
                        <button
                            key={i}
                            className={`shadow-md py-2 px-4 rounded-sm ${
                                page === i ? "bg-gray-600" : "bg-gray-800"
                            }`}
                            onClick={() => setPage(i)}
                        >
                            {pojoTab.className}
                        </button>
                    ))}
                </nav>
                <div className="container mx-auto py-4 lg:pb-8 flex flex-1">
                    <div className="flex flex-col w-full gap-2">
                        {page === -1 ? (
                            <JsonEditor
                                jsonInput={jsonInput}
                                setJsonInput={setJsonInput}
                            />
                        ) : (
                            <JavaEditor value={pojoClasses[page].value} />
                        )}
                        <button
                            onClick={generatePojo}
                            className="bg-indigo-600 hover:bg-indigo-500 transition duration-300 p-4 font-bold lg:text-xl rounded-sm"
                        >
                            Generate
                        </button>
                    </div>
                </div>
            </main>
        </>
    );
}
